@MinimalApiTutorial_HostAddress = https://localhost:7260

### Send request
GET {{MinimalApiTutorial_HostAddress}}/hello-get

### Send request
DELETE {{MinimalApiTutorial_HostAddress}}/hello-delete

POST {{MinimalApiTutorial_HostAddress}}/hello-post

###

POST {{MinimalApiTutorial_HostAddress}}/hello-post

###

GET {{MinimalApiTutorial_HostAddress}}/Newhello-get

###

GET {{MinimalApiTutorial_HostAddress}}/hello-get

###

GET {{MinimalApiTutorial_HostAddress}}/url

###

Get {{MinimalApiTutorial_HostAddress}}/api/students


###

Get {{MinimalApiTutorial_HostAddress}}/api/students/id


###

